#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

BASE=$OPENSHIFT_DIY_DIR
REPO=$OPENSHIFT_REPO_DIR
DATA=$OPENSHIFT_DATA_DIR

echo ""
echo "link the fcgi"
echo ""

export LD_LIBRARY_PATH=$DATA/lib
export NEKOPATH=$DATA/bin
$DATA/bin/nekotools boot $REPO/src/hello.n
mv $REPO/src/hello $REPO/www/index.fcgi
