#!/bin/bash

BASE=$OPENSHIFT_DIY_DIR
REPO=$OPENSHIFT_REPO_DIR
DATA=$OPENSHIFT_DATA_DIR

# check that supervisor is up
if ! [ -e $BASE/run/supervisord.sock ]; then
    echo "supervisor is not running"
    exit 0
fi

export PYTHONPATH="$DATA/pylibs/supervisor:$DATA/pylibs/meld3:$DATA/pylibs"
python $DATA/pylibs/supervisor/supervisorctl.py -c $DATA/etc/supervisor.ini status
