#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

echo 'starting processes'

DATA=$OPENSHIFT_DATA_DIR

export PYTHONPATH="$DATA/pylibs/supervisor:$DATA/pylibs/meld3:$DATA/pylibs"
export LD_LIBRARY_PATH=$DATA/lib
python $DATA/pylibs/supervisor/supervisord.py -c $DATA/etc/supervisor.ini

