#!/bin/bash
# The logic to stop your application should be put in this script.

echo 'stopping processes'

BASE=$OPENSHIFT_DIY_DIR
DATA=$OPENSHIFT_DATA_DIR

# check that supervisor is up
if ! [ -e $BASE/run/supervisord.sock ]; then
    echo "supervisor is not running"
    exit 0
fi

export PYTHONPATH="$DATA/pylibs/supervisor:$DATA/pylibs/meld3:$DATA/pylibs"
python $DATA/pylibs/supervisor/supervisorctl.py -c $DATA/etc/supervisor.ini shutdown

exit 0
