import neko.Web;
import neko.Lib;

class Hello
{
    static function main()
    {
        Web.cacheModule(run);
    }

    static function run()
    {
        Web.setHeader("Content-Type", "text/html");
        Lib.println("
<!DOCTYPE html>
<html>
<head>
<title>neko on openshift</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>hello</h1>

<p>this is a dynamic page generated by neko on the server.  that means
   supervisord, nginx, fastcgi and neko are all working.

<p>the params you passed on the querystring are: "+ Web.getParams()+"

</body>
</html>");
    }
}
